- name: Set up environment on remote machines
  hosts: remote
  roles:
    # Tag each role so that we can select individual roles to run with ansible-playbook --tags
    - { role: git, tags: ["git"] }
    - { role: package_manager, tags: ["package_manager", "bootstrap"] }
    - { role: zsh, tags: ["zsh", "bootstrap"] }
    - { role: python, tags: ["python"] }
    - { role: mise, tags: ["mise"] }
    - { role: rust, tags: ["rust"] }
    - { role: vim, tags: ["vim"] }
    - { role: rg, tags: ["rg"] }
    - { role: eza, tags: ["eza"] }
    - { role: gsed, tags: ["gsed"] }
    - { role: bat, tags: ["bat"] }
    - { role: fzf, tags: ["fzf"] }
    - { role: ollama, tags: ["ollama"] }
    - { role: beszel-agent, tags: ["beszel-agent"] }
    - { role: adguard, tags: ["adguard"] }
    - { role: lctl, tags: ["lctl"], when: ansible_os_family == "Darwin" }
    - { role: macos, tags: ["macos"], when: ansible_os_family == "Darwin" }
