---
- name: Create .local/bin directory if it doesn't exist
  file:
    path: "{{ dotfiles_user_home }}/.local/bin"
    state: directory

- name: Download beszel-agent
  get_url:
    url: "https://github.com/henrygd/beszel/releases/latest/download/beszel-agent_Darwin_arm64.tar.gz"
    dest: "{{ dotfiles_user_home }}/tmp/beszel-agent.tar.gz"
    mode: '0644'

- name: Extract beszel-agent archive
  command: "tar -xzf {{ dotfiles_user_home }}/tmp/beszel-agent.tar.gz -C {{ dotfiles_user_home }}/tmp"

- name: Copy beszel-agent binary to /opt/homebrew/bin
  copy:
    src: "{{ dotfiles_user_home }}/tmp/beszel-agent"
    dest: "/opt/homebrew/bin/beszel-agent"
    mode: '0755'
    remote_src: yes

- name: Clean up temporary files
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ dotfiles_user_home }}/tmp/beszel-agent.tar.gz"
    - "{{ dotfiles_user_home }}/tmp/beszel-agent"

- name: Create com.sloria.beszel-agent.plist in ~/Library/LaunchAgents
  template:
    src: "com.sloria.beszel-agent.plist.j2"
    dest: "{{ dotfiles_user_home }}/Library/LaunchAgents/com.sloria.beszel-agent.plist"

- name: Load beszel-agent service with launchctl
  command: launchctl load {{ dotfiles_user_home }}/Library/LaunchAgents/com.sloria.beszel-agent.plist
