- name: Install mise with homebrew
  homebrew: name=mise state=present

- name: Create mise config directory
  file:
    path: "{{ '~/.config/mise' | expanduser }}"
    state: directory
    mode: '0755'

- name: Copy mise config file
  copy:
    src: "{{ dotfiles_home }}/roles/mise/files/config.toml"
    dest: "{{ '~/.config/mise/config.toml' | expanduser }}"
